### ISSUE TITLE
EbeanPlugin: Add support for read-only data-sources

### ISSUE THREAD

**Issue by wsargent** [playframework/play-ebean#118]
Originally from https://github.com/playframework/playframework/issues/3237

Currently (Play 2.2, Play 2.3) when using multiple data-sources then it is not possible to disable evolutions and DDL automatic generation. This is usually not a problem, but becomes a problem with at least one of the sources being read-only.

There is a PR for disabling evolutions for specific data-sources, but there is no way to disable DDL generation per data-source. Only way is to disable EbeanPlugin DDL generation globally like this:

evolutionplugin=disabled
This does not solve the problem, because we want evolutions for non-read-only datasources.

Currently, when evolutionplugin is enabled (the default behavior) then evolution scripts are generated automatically by using DDL extraction here. The scripts are created and created and since this is a read-only datasource then they cannot be applied.

There should be a data-source specific option to disable automatic DDL generation.

PS! The option name evolutionplugin is also misleading for this particular use-case.

**Comment by tamanugi** [comment]
Any progress on this issue?

I got error 

```
Error trying to create the default EbeanServer
java.lang.RuntimeException: DataSource user is null?
	at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:207)
	at org.avaje.datasource.core.Factory.createPool(Factory.java:15)
	at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:334)
	at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:278)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:117)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:88)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:202)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:160)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:133)
	at io.ebean.Ebean.<clinit>(Ebean.java:127)
```


```java
package models;

import io.ebean.config.ServerConfig;
import io.ebean.event.ServerConfigStartup;
import org.avaje.datasource.DataSourceConfig;

public class MyServerConfigStartup implements ServerConfigStartup {

    @Override
    public void onStart(ServerConfig serverConfig) {
            serverConfig.setAutoReadOnlyDataSource(true);
        }
    }
}
```

Is there a workaround or correct setting?
