### ISSUE TITLE
DataSource is null in production only

### ISSUE THREAD

**Issue by vortexkd** [playframework/play-ebean#160]
**Java Version**: 9.0.4 (I tried on 10.0.2 as well)

**Play Version**: 2.6.15 (also 2.6.18)

**Play-ebean**: 4.1.3

The project runs fine with sbt run, but trying to run it in production (exactly the same environment), results in this error.

Any insight is appreciated! I hope this is the right place for this.

```
[warn] o.h.v.m.ParameterMessageInterpolator - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
[error] io.ebean.Ebean - Error trying to create the default EbeanServer
java.lang.RuntimeException: DataSource user is null?
        at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:207)
        at org.avaje.datasource.core.Factory.createPool(Factory.java:15)
        at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:334)
        at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:278)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:117)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:88)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
        at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
        at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:202)
        at io.ebean.Ebean$ServerManager.<init>(Ebean.java:160)
Oops, cannot start the server.
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
        at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:70)
        at com.google.inject.internal.Errors.formatSource(Errors.java:817)
        at com.google.inject.internal.Errors.formatSource(Errors.java:796)
        at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:849)
        at com.google.inject.internal.Errors.formatSource(Errors.java:811)
        at com.google.inject.internal.Errors.formatSource(Errors.java:796)
        at com.google.inject.internal.Errors.format(Errors.java:590)
        at com.google.inject.CreationException.getMessage(CreationException.java:50)
        at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
        at java.base/java.lang.Throwable.toString(Throwable.java:485)
        at java.base/java.lang.String.valueOf(String.java:2788)
        at java.base/java.io.PrintStream.println(PrintStream.java:897)
        at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
        at play.core.server.RealServerProcess.$anonfun$exit$1(ServerProcess.scala:49)
        at play.core.server.RealServerProcess.$anonfun$exit$1$adapted(ServerProcess.scala:49)
        at scala.Option.foreach(Option.scala:257)
        at play.core.server.RealServerProcess.exit(ServerProcess.scala:49)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:74)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.IllegalArgumentException
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:66)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:46)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:43)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
        ... 27 more

```

my conf set up looks like this:
```
db {
  default.driver=com.mysql.jdbc.Driver
  default.url="jdbc:mysql://<ip>/db_name?characterEncoding=UTF8&autoReconnect=true&useSSL=false"
  default.username=user
  default.password="pwd"
}
```

**Comment by vortexkd** [comment]
#51 
Like the issue described here, the prod mode works sometimes, and crashes on launch sometimes so it seems to be related.
The solution here, Injecting both DynamicEvolutions and EbeanConfig seems to solve my problem.

**Comment by lapidus79** [comment]
Closed since solution provided by vortexkd
