### ISSUE TITLE
[2.7.0-RC8][5.0.0-RC2] Evolution fails for auto-generated script contains create procedures script

### ISSUE THREAD

**Issue by almothafar** [playframework/play-ebean#166]
### Play Version
2.7.0-RC8

### API 
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
WIndows 10 64-bit Enterprise 

### JDK 

```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

### Library Dependencies

I tried to use MySQL and MariaDB:

```
  "org.mariadb.jdbc" % "mariadb-java-client" % "2.3.0",
  "mysql" % "mysql-connector-java" % "8.0.13",
```

### Expected Behavior

1. Create entities for ebean and configure it in the application.conf file:

```
db.default.driver = com.mysql.cj.jdbc.Driver
db.default.url = "jdbc:mysql://localhost:3306/mydb?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false"
db.default.username = "username"
db.default.password = "passowrd"

play.evolutions.db.default.enabled = true
play.evolutions.db.default.autoApply = true
play.evolutions.db.default.autoApplyDowns = false
```

Also tried:
```
db.default.driver = org.mariadb.jdbc.Driver
db.default.url = "jdbc:mariadb://localhost:3306/mydb?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false"
```

2. Run application waiting for 1.sql to auto-generate the script, the first line of 1.sql should be:

```sql
# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

```
3. sql script generated and it should be run the application without any issue with the newly created script.

### Actual Behavior

The problem is that script contains `CREATE PROCEDURE`!
If I run the file manually it will be executed without any issues, but play evolution service can't run it, and it fails.

The first part of the file will be:

```mysql

-- init script create procs
-- Inital script to create stored procedures etc for mysql platform
DROP PROCEDURE IF EXISTS usp_ebean_drop_foreign_keys;

delimiter $$
--
-- PROCEDURE: usp_ebean_drop_foreign_keys TABLE, COLUMN
-- deletes all constraints and foreign keys referring to TABLE.COLUMN
--
CREATE PROCEDURE usp_ebean_drop_foreign_keys(IN p_table_name VARCHAR(255), IN p_column_name VARCHAR(255))
BEGIN
  DECLARE done INT DEFAULT FALSE;
  DECLARE c_fk_name CHAR(255);
  DECLARE curs CURSOR FOR SELECT CONSTRAINT_NAME from information_schema.KEY_COLUMN_USAGE
    WHERE TABLE_SCHEMA = DATABASE() and TABLE_NAME = p_table_name and COLUMN_NAME = p_column_name
      AND REFERENCED_TABLE_NAME IS NOT NULL;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

  OPEN curs;

  read_loop: LOOP
    FETCH curs INTO c_fk_name;
    IF done THEN
      LEAVE read_loop;
    END IF;
    SET @sql = CONCAT('ALTER TABLE ', p_table_name, ' DROP FOREIGN KEY ', c_fk_name);
    PREPARE stmt FROM @sql;
    EXECUTE stmt;
  END LOOP;

  CLOSE curs;
END
$$

DROP PROCEDURE IF EXISTS usp_ebean_drop_column;

delimiter $$
--
-- PROCEDURE: usp_ebean_drop_column TABLE, COLUMN
-- deletes the column and ensures that all indices and constraints are dropped first
--
CREATE PROCEDURE usp_ebean_drop_column(IN p_table_name VARCHAR(255), IN p_column_name VARCHAR(255))
BEGIN
  CALL usp_ebean_drop_foreign_keys(p_table_name, p_column_name);
  SET @sql = CONCAT('ALTER TABLE ', p_table_name, ' DROP COLUMN ', p_column_name);
  PREPARE stmt FROM @sql;
  EXECUTE stmt;
END
$$

```

The console output:

```console
2018-12-13 14:27:10 +0200 80902 ERROR p.a.d.e.DefaultEvolutionsApi - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delimiter $$
--
-- PROCEDURE: usp_ebean_drop_foreign_keys TABLE, COLUMN
-- delet' at line 1 [ERROR:1064, SQLSTATE:42000]
2018-12-13 14:27:11 +0200 81207 ERROR application - 

! @7a8adme52 - Internal server error, for (GET) [/] ->
 
play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
	at play.api.db.evolutions.DatabaseEvolutions.$anonfun$checkEvolutionsState$3(EvolutionsApi.scala:293)
	at play.api.db.evolutions.DatabaseEvolutions.$anonfun$checkEvolutionsState$3$adapted(EvolutionsApi.scala:278)
	at play.api.db.evolutions.DatabaseEvolutions.executeQuery(EvolutionsApi.scala:325)
	at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:278)
	at play.api.db.evolutions.DatabaseEvolutions.evolve(EvolutionsApi.scala:247)
	at play.api.db.evolutions.DefaultEvolutionsApi.evolve(EvolutionsApi.scala:97)
	at play.api.db.evolutions.ApplicationEvolutions.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:63)
	at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:100)
	at play.api.db.evolutions.ApplicationEvolutions.runEvolutions(ApplicationEvolutions.scala:49)
	at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1$adapted(ApplicationEvolutions.scala:42)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:151)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:50)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:49)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:40)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:241)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:138)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$26.onPush(Ops.scala:1304)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

![image](https://user-images.githubusercontent.com/13887564/49939284-164e5b80-fee5-11e8-8cf5-e5e42f15d5fe.png)

### Reproducible Test Case

Can be reproduced with my fork here: https://github.com/almothafar/play-with-mapstruct/tree/play-2.7.x 

----------
**More info with full details provided here**: https://github.com/playframework/playframework/issues/8879

**Comment by marcospereira** [comment]
Okay, so, what is the modern way of doing migrations in Ebean these days?

**Comment by almothafar** [comment]
@marcospereira not sure, you tell me 😁, that thing is just added with ebean version 11.19.1 as I see from history and releases here: https://github.com/ebean-orm/ebean/releases/tag/ebean-11.19.1 

I think the current play version (2.6.20) use version 11.15.something.

**Comment by marcospereira** [comment]
Thanks for joining the conversation, @rbygrave.

> Ebean started using procedures to assist with the migration DDL for mysql and sql server in particular

Is there a way to disable it? Asking since Play has its own way to run the migration, so I don't think the procedures would be useful here at first. The path you described sounds reasonable to me. It needs to happen in the context of this project instead of Play itself so changes should be made here.

Also, we don't have the resources to make it happen now. So, contributions would be welcome here.

**Comment by almothafar** [comment]
@marcospereira sorry I meant play's one, meaning play-ebean not play itself.

So are we moving back to play for the evolution parse? https://github.com/playframework/playframework/blob/683dc2c65d5daa463a3ffe2fb56157228cb8db8b/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala#L59

**Comment by marcospereira** [comment]
> So are we moving back to play for the evolution parse?

No. The evolutions API is extensible in a way that Play Ebean can provide its bindings overriding the default one. This includes the evolutions parsing.

**Comment by renatocaval** [comment]
@almothafar, this should be fixed on the lasted release 5.0.0-RC3 that is using Play 2.7.0-RC9. 

I'm closing it, therefore.

**Comment by mkurz** [comment]
@renatocaval Are you sure this is fixed? This has nothing to do with my evolution fixes. As I understand it this is a problem with ebean generating procedures and within that procudures the semicolon are not escaped (that has do be done manually).

**Comment by renatocaval** [comment]
Oh, maybe I went to fast with that. I saw `[2.7.0-RC8][5.0.0-RC2]` in the title and assumed it was related with that other issue. 

Reopening...

**Comment by AlbaroPereyra** [comment]
The issues still exists.

**Comment by zoyaforever** [comment]
I also have this problem in Play 2.7.0

**Comment by AlbaroPereyra** [comment]
The issue is very annoying and makes 2.7 unusable for creating new projects, that require a lot of debugging. I had to downgrade to 2.6.

**Comment by AlbaroPereyra** [comment]
I am unable to find a link to a post I read, regarding a workaround. I was unable to make it work but, at a glance it makes sense.

Basically the post mentioned to skip using play-ebean creation by creating a basic access test using https://mvnrepository.com/artifact/io.ebean.test/ebean-test-config

**Comment by sevensevener** [comment]
Also working on 2.7, is there a chance this is getting fixed withing the next time? Or should i also migrate to 2.6? Im kinda new to Play, is 2.7 even stable?

**Comment by marcospereira** [comment]
> Im kinda new to Play, is 2.7 even stable

Yes, it is.

The problem here is not with Play itself, but with the integration between Play and Ebean, which is a separated module with its own issue tracker, releases, etc.

> Also working on 2.7, is there a chance this is getting fixed withing the next time?

Depends on contributions if you want to accelerate it. The integration with Ebean is not a priority for us right now.

**Comment by almothafar** [comment]
OK, now I got a strange issue with MSSQL (Microsoft SqlServer), it is adding `delimiter $$` even it is not correct, with:

package models;

```
import io.ebean.config.ServerConfig;
import io.ebean.event.ServerConfigStartup;

public class EbeanServerConfigStartup implements ServerConfigStartup {
    public void onStart(ServerConfig serverConfig) {
        serverConfig.setDatabasePlatformName("sqlserver17");
    }
}

```

And:

```
db.default.driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
db.default.url = "jdbc:sqlserver://SRV_IP:1433;databaseName=DB"
db.default.jdbc-url = "jdbc:sqlserver://SRV_IP:1433;databaseName=DB"
db.default.username = "SA"
db.default.password = "PASSWORD"
```

Any idea?

**Comment by hiroya8649** [comment]
Hi. I'm new to play (and also java). I met this problem too and felt very upset because I spent almost two days to try. Then I realize it has been an issue now.

I'm now considering downgrade or giving up using play.

**Comment by AlbaroPereyra** [comment]
@hiroya8649 

I would downgrade if I were you.

I continued my development in 2.6 and thus far the only disadvantage I foresee is having to refactor the code to the latest version once this is fixed.

**Comment by hiroya8649** [comment]
@AlbaroPereyra Thanks for advice.

I found someone said there is the same issue in 2.6.20,.May I ask what version of play / play-ebean do you use?

**Comment by AlbaroPereyra** [comment]
I’m using version 2.6, I installed the latest 2.6 and ebeans plugin 2 months ago. I will login to my server and let you know exactly what version that is later.

**Comment by AlbaroPereyra** [comment]
@hiroya8649 I’m using Play 2.6.21 and sbt-play-ebean 4.1.3

Let me what files you would like to see to help you get up and running. I am planing to open source this project once I am done with it anyways.

**Comment by hiroya8649** [comment]
@AlbaroPereyra Sorry for late. I have set up a new project with the version you said and got it working yesterday. 
Thanks again!

**Comment by cyrilfr** [comment]
Any fix planned for this issue? I wanted to upgrade from Play 2.5 to 2.7 but I'm gonna give up...

**Comment by marcospereira** [comment]
> Any fix planned for this issue?

No, this is not a priority for us now. But contributions are welcome.

**Comment by cyrilfr** [comment]
> > Any fix planned for this issue?
> 
> No, this is not a priority for us now. But contributions are welcome.

I would love to contribute but my level in Scala programming isn't good enough. What's the preferred ORM for Play 2.7 so?

**Comment by mkurz** [comment]
This is fixed now with latest play-ebean, because it upgrades ebean to version `11.45.1`: #192
Starting with that ebean version no stored procedure will be generated automatically anymore by default: https://github.com/ebean-orm/ebean/issues/1802 and https://github.com/ebean-orm/ebean/pull/1815

**Comment by almothafar** [comment]
@mkurz   That's only for MySQL, for MSSQL here it is still doing it, also no need to spread comments to all tickets :)

**Comment by zhaoenhz** [comment]
i use `source /Users/xx/workspace/xx/conf/evolutions/default/1.sql ` in mysql client, the generated sql is correct, the tables created, but evolution has not been applied properly.

**Comment by zhaoenhz** [comment]
delimiter is a command for SQL client, JDBC does not support the delimiter command

**Comment by A-L-Fearon** [comment]
Hi, was an updated solution or workaround for this ever found? appears to still persist in latest version 8.3.0.

**Comment by mkurz** [comment]
No solution so far.
However thinking about this, maybe we can solve problems like this once and for all if Play's evolutions reader would be able to handle special "meta data" within sql scripts like:

```sql
-- !Play-Evolutions: KEEP SEMICOLONS START
// semicolons within this sql block should be kept as they are
-- !Play-Evolutions: KEEP SEMICOLONS END
```

For ebean that would mean:

```sql
CREATE PROCEDURE usp_ebean_drop_foreign_keys(IN p_table_name VARCHAR(255), IN p_column_name VARCHAR(255))
BEGIN
-- !Play-Evolutions: KEEP SEMICOLONS START
DECLARE done INT DEFAULT FALSE;
DECLARE c_fk_name CHAR(255);
DECLARE curs CURSOR FOR SELECT CONSTRAINT_NAME from information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE() and TABLE_NAME = p_table_name and COLUMN_NAME = p_column_name
AND REFERENCED_TABLE_NAME IS NOT NULL;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

OPEN curs;

read_loop: LOOP
FETCH curs INTO c_fk_name;
IF done THEN
LEAVE read_loop;
END IF;
SET @sql = CONCAT('ALTER TABLE `', p_table_name, '` DROP FOREIGN KEY ', c_fk_name);
PREPARE stmt FROM @sql;
EXECUTE stmt;
END LOOP;

CLOSE curs;
-- !Play-Evolutions: KEEP SEMICOLONS END
END
$$
```

I just opened

- https://github.com/ebean-orm/ebean/pull/3408

to discuss this approach with @rbygrave, lets see how this turns out.

**Comment by ihostage** [comment]
So, https://github.com/ebean-orm/ebean/pull/3408 was released and we can continue 😉
