### ISSUE TITLE
Compatibility Play 2.8

### ISSUE THREAD

**Issue by Flo354** [playframework/play-ebean#189]
Hi there,

Is it possible to make play-ebean compatible with Play 2.8.0?

Thanks,

**Comment by PromanSEW** [comment]
https://github.com/playframework/playframework/issues/9922

**Comment by Flo354** [comment]
Hey @marcospereira, Hey @mkurz,

Is this project still maintained?

Thanks :)

**Comment by renatocaval** [comment]
The project is Community Driven. 

See https://github.com/playframework/play-ebean#support

**Comment by Flo354** [comment]
Hmm... Okay.
I don't really understand why, but ok.
I guess I'll have to find another alternative.

Thanks for your answer @renatocaval

**Comment by marcospereira** [comment]
>  I don't really understand why, but ok.

It is what was happening already. We are a small team maintaining Play & Lagom, and there are other things we consider more relevant than Ebean integration. Luckily, https://github.com/payintech/play-ebean fork was kept up to date with Ebean at least, and I would suggest contributing there if Play 2.8.0 support is crucial for you.

Best.

**Comment by renatocaval** [comment]
@Flo354, the reason is the amount of interest in it. We have enough projects to manage and if there is one that is used by a small part of the community, it ends up getting less attention, fewer bug reports, fewer bug fixes, etc. Not only less attention from us, from the whole community in general. 

Moreover, [payintech/play-ebean](https://github.com/payintech/play-ebean), which is a fork of [playframework/play-ebean](https://github.com/playframework/play-ebean), is much more up-to-date. 

I don't know why the maintainers of the fork didn't send pull-request to this project here or stepped in to become the main maintainers. Anyway, that's another discussion. 

If you are looking for alternatives, I good place to start is [payintech/play-ebean](https://github.com/payintech/play-ebean).

**Comment by Flo354** [comment]
Thanks for your answers!
It also seems that payintech doesn't maintain this project anymore. It's sad but I understand there are other priorities.

It will be difficult for the future.

**Comment by lapidus79** [comment]
I made a fork @ https://github.com/lapidus79/play-ebean

**Comment by Flo354** [comment]
Hi @lapidus79,

Thanks for your fork. Awesome!

However, I still have issues with Java 11.

```
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
  while locating play.api.db.evolutions.ApplicationEvolutionsProvider
  at play.api.db.evolutions.EvolutionsModule.<init>(EvolutionsModule.scala:23):
Binding(class play.api.db.evolutions.ApplicationEvolutions to ProviderConstructionTarget(class play.api.db.evolutions.ApplicationEvolutionsProvider) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  while locating play.api.db.evolutions.ApplicationEvolutions

1 error]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:210)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:141)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:296)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1261)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
  while locating play.api.db.evolutions.ApplicationEvolutionsProvider
  at play.api.db.evolutions.EvolutionsModule.<init>(EvolutionsModule.scala:23):
Binding(class play.api.db.evolutions.ApplicationEvolutions to ProviderConstructionTarget(class play.api.db.evolutions.ApplicationEvolutionsProvider) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  while locating play.api.db.evolutions.ApplicationEvolutions

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:211)
	at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:121)
	at play.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.java:32)
	at play.api.ApplicationLoader$JavaApplicationLoaderAdapter$1.load(ApplicationLoader.scala:179)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:189)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:181)
	... 24 common frames omitted
Caused by: java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.read(ExtraDdlXmlReader.java:147)
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.read(ExtraDdlXmlReader.java:130)
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.readBuiltin(ExtraDdlXmlReader.java:103)
	at io.ebeaninternal.dbmigration.model.CurrentModel.getCreateDdl(CurrentModel.java:144)
	at play.db.ebean.EbeanDynamicEvolutions.generateEvolutionScript(EbeanDynamicEvolutions.java:93)
	at play.db.ebean.EbeanDynamicEvolutions.lambda$create$3(EbeanDynamicEvolutions.java:59)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at play.db.ebean.EbeanDynamicEvolutions.create(EbeanDynamicEvolutions.java:58)
	at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:56)
	at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:107)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:67)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:60)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:51)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	... 35 common frames omitted
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.read(ExtraDdlXmlReader.java:142)
	... 56 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
	... 60 common frames omitted

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

I have to include the following lines in my build.sbt to be able to run the app.

```
"org.glassfish.jaxb" % "jaxb-core" % "2.3.0.1",
"org.glassfish.jaxb" % "jaxb-runtime" % "2.3.2"
```

Do you have an idea how to fix this?

Thanks,

**Comment by lapidus79** [comment]
> javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.

what if you add 

libraryDependencies += "javax.xml" % "jaxb-api" % "2.1" 

as mention in

https://stackoverflow.com/questions/51916221/javax-xml-bind-jaxbexception-implementation-of-jaxb-api-has-not-been-found-on-mo

**Comment by lapidus79** [comment]
How about using jaxb-runtime only?

https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154

**Comment by Flo354** [comment]
Maybe it will work, but I would prefer not to use these dependencies.
It would be better to support java 11 "out of the box" without re-inserting these dependencies that were removed.

**Comment by renatocaval** [comment]
@lapidus79, would you like to step in as maintainer of https://github.com/playframework/play-ebean?
Of course, you can fork but if you plan to dedicate time to it, the best would be to bring the changes in here so others can benefit. 

A maintainer doesn't need to be someone from the Play team at Lightbend. Any community member can take on the task. For instance, github.com/playframework/play-soap has @ihostage as the main maintainer.

The only difference is that the releases will still be managed by us, but this is mostly ok.

**Comment by mowcixo** [comment]
I think maintain the official repo is always better, collaborating with PR's. I've made this myself in this repo and the releases was so fast deployed by the Play team.

**Comment by renatocaval** [comment]
The best here is to have more than one maintainer from outside Lightbend Play's team. As such, whenever we are overloaded doing some other work, the other maintainers can review and merge each other PRs. 

Releasing is still a bottleneck, but we can also work on that. We have been trying to improve it in play-soap, but we are not yet there. 

Who wants to take the challenge? @mowcixo / @lapidus79, should we add you both as maintainers of play-ebean.

**Comment by lapidus79** [comment]
@Flo354 There is now a 5.0.4 at my repo which included jaxb-runtime as a dependency so no need to add it explicitly.

However, I at least encountered some issues with the play-enhancer on java 11 https://github.com/playframework/play-enhancer. Got some issues with javaassit having problems with javax.sql.Timestamp. Seems that the javaassist version is quite old. Anyhow you can disable the playEnhancer with .settings(playEnhancerEnabled := false).

Regarding the JAXP issue seems that isJavaxJAXBPresent() method in https://github.com/ebean-orm/ebean/commit/a6f9120905825476d7f1c99071f175a5b46ad614 for some reason returns true on Java 11, even tough it's not preset.

@renatocaval I'm in

**Comment by Flo354** [comment]
That's awesome guys, thanks! This module will continue his way.
If I knew how to code in Scala, I would defintely maintain it, but I don't, so thanks @lapidus79 for your time!

@lapidus79, don't you think it would be better to have full compatibility without including jaxb-runtime as a dependency?

Don't know if it's possible if the problem comes from ebean directly.

**Comment by renatocaval** [comment]
@lapidus79, I created a new team called "Play Ebean Integrators". You were added to it. As a maintainer, you get admin rights on this repo. You can merge PRs, close PRs, add labels and add other collaborators. Welcome!

@Flo354, helping on an open-source project is the best way to learn new skills. You don't need to be proficient in Scala to become part of it. You can assist @lapidus79, by doing code review. It's up to you if you want we can add you as well.

**Comment by Flo354** [comment]
@renatocaval  as of today, it would be useless because I'm not only expert in Scala, I am also before beginner (I never wrote a single code in Scala).

But thanks! I think we can close this issue if you all agree.

**Comment by lapidus79** [comment]
I'll leave it open until we have an official 2.8.0 play-ebean released and not just my hack.

**Comment by jmswenski** [comment]
Hi there! I'd be interested in helping out! My team uses play and play-ebean internally and we're open to submitting patches upstream / helping review new work!

**Comment by lapidus79** [comment]
Awesome @jmswenski I've added you to the project. There is a PR for play 2.8.0 ready for review https://github.com/playframework/play-ebean/pull/192

**Comment by jmswenski** [comment]
Awesome, will check it out and have some of my team try it out internally

**Comment by renatocaval** [comment]
@lapidus79, I reviewed it already and merged.
@jmswenski, I added to the play-ebean intergrators team. You had already access since @lapidus79 added you directly. But now you are also part of the team.

Great that we have already two maintainers willing to take care of this project. Thanks for stepping in.

**Comment by getv** [comment]
Hey guys! Amazing work. Is 6.0.0 actually released?
When I add it to my project with this line `addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.0.0")` I get:

> sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-play-ebean;sbtVersion=1.0;scalaVersion=2.12:6.0.0
> Not found
> not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-play-ebean_2.12_1.0/6.0.0/sbt-play-ebean-6.0.0.pom

**Comment by lapidus79** [comment]
@getv not yet. As a temporary solution you can use the https://github.com/lapidus79/play-ebean. 

@renatocaval when can we expect to get the release published to maven central?

**Comment by renatocaval** [comment]
@lapidus79, Is it ready for the next release? 

We need to schedule that, but usually it doesn't take too long. Normally, if you ping me, I can release it on the same day.

**Comment by renatocaval** [comment]
@lapidus79, I guess you were only waiting for https://github.com/playframework/play-ebean/pull/192 to be merged?

And you want to cut release 6.0.0 which is the one to be used with Play 2.8.x series.  Correct?

**Comment by lapidus79** [comment]
@renatocaval yes and yes :)

**Comment by mkurz** [comment]
@renatocaval FYI 6.0.0 is already tagged: https://github.com/playframework/play-ebean/releases/tag/6.0.0

**Comment by renatocaval** [comment]
hmm, ok. I will have to check it now. We don't release by tag yet, so we may need to do some tricks now.

**Comment by lapidus79** [comment]
@renatocaval yea the tag is not of importance. Only thought it might trigger a publish flow or similiar. Just do it how you usually do it.

**Comment by renatocaval** [comment]
We do the releases from a special machine we have, but we want to change that. 

I tried to do it today but got an error and I didn't have time to look further. Will try again tomorrow.

The next step for this repo is to add github.com/dwijnand/sbt-dynver and release by tag. Then, the releases will go to bintray and we can sync it to maven. 

As such, you will be able to cut releases yourself and depend on us only to sync to maven central. That's the ultimate goal.

**Comment by renatocaval** [comment]
@lapidus79, the release is done and should appear at maven central in a few minutes.

**Comment by lapidus79** [comment]
@renatocaval awesome, thank you
