### ISSUE TITLE
Support java14

### ISSUE THREAD

**Issue by apflieger** [playframework/play-ebean#194]
Hello,

I found an incompatibility while upgrading my play project to java14. This plugin depends on a version of ebean-agent that doesn't allow java14.

Here's what the current version does https://github.com/ebean-orm/ebean-agent/blob/1aa70aeab69afd95afa849db8ee1eb5e00021671/src/main/java/io/ebean/enhance/asm/ClassReader.java#L182
It has been updated here https://github.com/ebean-orm/ebean-agent/commit/66a13c9c067054bc7bf7afdf0cfad2856406f4aa#diff-94e2228d56b0ae1bef52d3e21f9e81d1R194
Available in at least ebean-agent-12.1.11

**Comment by jmswenski** [comment]
@apflieger - created a PR for this. Tested it out this afternoon on our stack and got our play 2.8.x app up working with Java14. Hooray exhaustive switch! Hopefully we can get this merged and let people choose to use it if they wish even though Java14 isn't an LTS release

**Comment by jmswenski** [comment]
https://bintray.com/playframework/sbt-plugin-releases/play-ebean/6.1.0-RC2

Release candidate up in bintray if you want to try it out

**Comment by Santhoshas** [comment]
I am getting the below error while compiling the project using sbt. Which version is invalid here? 

sbt -> 1.3.13
scala -> 2.12.13
Play -> 2.7.0
JDK -> 15
addSbtPlugin("com.typesafe.sbt" % "sbt-play-enhancer" % "1.2.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "5.0.2")

Error:
java.lang.IllegalArgumentException: Unsupported class file major version 59
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:184)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:152)
	at io.ebean.enhance.Transformer.detect(Transformer.java:352)
	at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:187)
	at io.ebean.enhance.Transformer.transform(Transformer.java:152)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
	at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:84)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)



java.lang.IllegalArgumentException: Unsupported class file major version 59
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:184)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:152)
	at io.ebean.enhance.Transformer.detect(Transformer.java:352)
	at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:187)
	at io.ebean.enhance.Transformer.transform(Transformer.java:152)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
	at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:84)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)

**Comment by jmswenski** [comment]
@Santhoshas - this issue potentially adds support for Java14. I don't think we can go to 15 yet due to some dependence on ASM. I think mainly I'm going to try supporting the same versions as Play right now which is 8/11 anyhow as the LTS cadence makes more sense to support.
