### ISSUE TITLE
Remove (or update) sbt-play-enhancer dependency

### ISSUE THREAD

**Issue by Flo354** [playframework/play-ebean#201]
Hello there,

I updated to SBT 1.4.1 today and unfortunately, my play project doesn't compile anymore.
Here is the stack trace:

```
[IJ][database] $ last manipulateBytecode
[error] java.lang.NoSuchMethodError: 'scala.collection.immutable.Set sbt.internal.inc.Relations.classNames(java.io.File)'
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$bytecodeEnhance$4(PlayEnhancer.scala:80)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.getClassesForSources$1(PlayEnhancer.scala:76)
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$bytecodeEnhance$3(PlayEnhancer.scala:91)
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$scopedSettings$3(PlayEnhancer.scala:51)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / manipulateBytecode) java.lang.NoSuchMethodError: 'scala.collection.immutable.Set sbt.internal.inc.Relations.classNames(java.io.File)'
```

sbt-play-enhancer has been archived and is not maintained anymore. Could we get rid of this dependency?

**Comment by jmswenski** [comment]
I addressed this in #203

**Comment by kaos** [comment]
is there a work-around one can apply to force exclude sbt-play-enhancer, or something like that?

**Comment by CEikermann** [comment]
@octonato after this issue was solved by https://github.com/playframework/play-ebean/pull/203 - guess these changes will land in 6.1.0 is that right?

Do you have already an ETA when this version will be available in bintray/maven?

**Comment by CEikermann** [comment]
@jmswenski do you have already an ETA when the version with that fix will be available in bintray/maven?

**Comment by jmswenski** [comment]
There is a release candidate up at Bintray @CEikermann 

https://bintray.com/playframework/sbt-plugin-releases/play-ebean/6.1.0-RC2

You'll need to use bintray resolvers though since that release isn't in maven central

```
resolvers += Resolver.bintrayRepo("playframework", "maven")
resolvers += Resolver.bintrayRepo("playframework", "sbt-plugin-releases")
```

I'd love your feedback on this release candidate, I've recently taken over this repository as the maintainer and we're working on the release process right now so it's hard to say when I'll have this release up in maven central. N.B. this release removes the enhancer as a dependency, but I haven't tested it with sbt 1.4.x yet - I think there are a few more changes required to make it work with the latest sbt.

**Comment by CEikermann** [comment]
@jmswenski 
Just tested 6.1.0-RC2 but sadly we are getting an compile error:
[error] java.lang.UnsupportedClassVersionError: play/db/ebean/ModelsConfigLoader has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Does 6.1.0-RC2 not support Java 8 anymore?

**Comment by jmswenski** [comment]
@cchantep - hmm, looks like the auto-deployment built everything with Java 11. I don't think that was intentional on my part. Will change it so it builds with Java 8 instead since we're not using any Java 11 features in this project and put up another RC soon.

**Comment by CEikermann** [comment]
@jmswenski do you have an update on the current progress on this?

> @jmswenski
> Just tested 6.1.0-RC2 but sadly we are getting an compile error:
> [error] java.lang.UnsupportedClassVersionError: play/db/ebean/ModelsConfigLoader has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 
> Does 6.1.0-RC2 not support Java 8 anymore?

**Comment by Flo354** [comment]
Hello @jmswenski,

I just can't find a way to sync the release candidate. Here is my `plugins.sbt` 

```sbt
resolvers += Resolver.bintrayRepo("playframework", "maven")
resolvers += Resolver.bintrayRepo("playframework", "sbt-plugin-releases")

// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.7")
addSbtPlugin("com.typesafe.play" % "play-ebean" % "6.1.0-RC2")
```

```
[info] welcome to sbt 1.4.5 (Ubuntu Java 11.0.9.1)
[info] loading settings for project global-plugins from sbt-updates.sbt ...
[info] loading global plugins from /home/florian/.sbt/1.0/plugins
[info] loading settings for project database-build from plugins.sbt ...
[info] loading project definition from /home/florian/Desktop/arcansecurity/java/com/arcansecurity/play/base/database/project
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.play:play-ebean:6.1.0-RC2 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean;sbtVersion=1.0;scalaVersion=2.12:6.1.0-RC2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/play-ebean-6.1.0-RC2.pom
[error]   not found: /home/florian/.ivy2/local/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.1.0-RC2/ivys/ivy.xml
[error]   not found: https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/play-ebean-6.1.0-RC2.pom
[error]   not found: https://dl.bintray.com/playframework/sbt-plugin-releases/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/play-ebean-6.1.0-RC2.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.1.0-RC2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.1.0-RC2/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean;sbtVersion=1.0;scalaVersion=2.12:6.1.0-RC2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/play-ebean-6.1.0-RC2.pom
[error]   not found: /home/florian/.ivy2/local/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.1.0-RC2/ivys/ivy.xml
[error]   not found: https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/play-ebean-6.1.0-RC2.pom
[error]   not found: https://dl.bintray.com/playframework/sbt-plugin-releases/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/play-ebean-6.1.0-RC2.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.1.0-RC2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.1.0-RC2/ivys/ivy.xml
```

It seems that it's keep searching for url `https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.12_1.0/6.1.0-RC2/` instead of `https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.13/6.1.0-RC2/`

I tried something like : 
```sbt
addSbtPlugin("com.typesafe.play" % "play-ebean" % "6.1.0-RC2", sbtVersion = "1.0", scalaVersion = "2.13")
OR
addSbtPlugin("com.typesafe.play" % "play-ebean" % "6.1.0-RC2", sbtVersion = "", scalaVersion = "2.13")
```

But same effect. Could you help figure the problem out? Thanks,

**Comment by mkurz** [comment]
@Flo354 
You made mistake, its _not_:
```
addSbtPlugin("com.typesafe.play" % "play-ebean" % "6.1.0-RC2")
```
it is:
```
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC2")
```
that should go into your `project/plugins.sbt`

**Comment by Flo354** [comment]
@mkurz thanks for your answer, but it does not work either.

```sbt
resolvers += Resolver.bintrayRepo("playframework", "maven")
resolvers += Resolver.bintrayRepo("playframework", "sbt-plugin-releases")

// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.7")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC2")

...
```

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean_2.13:6.1.0-RC2
[error]   Not found
[error]   Not found
[error]   not found: /home/florian/.ivy2/local/com.typesafe.play/play-ebean_2.13/6.1.0-RC2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.13/6.1.0-RC2/play-ebean_2.13-6.1.0-RC2.pom
[error]   not found: /home/florian/.m2/repository/com/typesafe/play/play-ebean_2.13/6.1.0-RC2/play-ebean_2.13-6.1.0-RC2.pom
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean_2.13:6.1.0-RC2
[error]   Not found
[error]   Not found
[error]   not found: /home/florian/.ivy2/local/com.typesafe.play/play-ebean_2.13/6.1.0-RC2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.13/6.1.0-RC2/play-ebean_2.13-6.1.0-RC2.pom
[error]   not found: /home/florian/.m2/repository/com/typesafe/play/play-ebean_2.13/6.1.0-RC2/play-ebean_2.13-6.1.0-RC2.pom
[error] Total time: 9 s, completed 24 mars 2021 à 17:09:43
[info] shutting down sbt server

```

**Comment by mkurz** [comment]
@Flo354 
Put this in your `build.sbt`
```
resolvers += Resolver.bintrayRepo("playframework", "maven")
```
Actually I think that is the _only_ resolver you need, I am pretty sure you can remove the other two resolvers from your `project/plugins.sbt`

**Comment by almothafar** [comment]
@mkurz 

Still, not working, I'm getting the following error

```console
Extracting structure failed
stack trace is suppressed; run 'last updateSbtClassifiers' for the full output
(updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
https://repo1.maven.org/maven2/tyrex/tyrex/1.0.1/tyrex-1.0.1-sources.jar: not found: https://repo1.maven.org/maven2/tyrex/tyrex/1.0.1/tyrex-1.0.1-sources.jar
https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar: not found: https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
Total time: 1 s, completed Mar 29, 2021, 12:50:05 PM
```

**Comment by Flo354** [comment]
@mkurz it works now for me. Thanks!

@almothafar your error seems related to other dependencies than ebean.
