### ISSUE TITLE
NoSuchMethodError: sbt.internal.inc.Relations.classNames(Ljava/io/File;)Lscala/collection/immutable/Set;

### ISSUE THREAD

**Issue by PromanSEW** [playframework/play-ebean#214]
I don't know the right place for this issue, because error in Play Enhancer, which is archived
Play 2.8.8, SBT 1.5.0, Scala 2.12.13:

```
[error] java.lang.NoSuchMethodError: sbt.internal.inc.Relations.classNames(Ljava/io/File;)Lscala/collection/immutable/Set;
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$bytecodeEnhance$4(PlayEnhancer.scala:80)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.getClassesForSources$1(PlayEnhancer.scala:76)
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$bytecodeEnhance$3(PlayEnhancer.scala:91)
[error] 	at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$scopedSettings$3(PlayEnhancer.scala:51)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / manipulateBytecode) java.lang.NoSuchMethodError: sbt.internal.inc.Relations.classNames(Ljava/io/File;)Lscala/collection/immutable/Set;
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:775)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:790)

```

**Comment by PromanSEW** [comment]
Checked Play 2.8.7 with Scala 2.12.12 and SBT 1.4.3 - the same error
SBT 1.3.13 - works fine

**Comment by mkurz** [comment]
There is a 6.1.0 release candidate you can use:

`project/plugins.sbt`:
```
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC2")
```
and in your `build.sbt`:
```
resolvers += Resolver.bintrayRepo("playframework", "maven")
```

I think there is already RC3 out, so you might want to try `6.1.0-RC3`.

**Comment by mkurz** [comment]
Also see #208

**Comment by almothafar** [comment]
The problem from my side is 6.1.0 uses the latest ebean as well, which is perfect, so it is no more need ebean.properties, but application.properties, providing that will cause issue #212

**Comment by nitin-cloudfinch** [comment]
2.13.6

> Checked Play 2.8.7 with Scala 2.12.12 and SBT 1.4.3 - the same error
> SBT 1.3.13 - works fine

This worked for me. It also worked with Scala 2.13.6

**Comment by jmswenski** [comment]
Good news is SBT 1.4.x+ will work as soon as we can get #208 merged in too. I'd like the Sonatype deployments finish up first though.

**Comment by justinnichols** [comment]
I'm getting this (replaced my home folder with ~)...
```
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean_2.13:6.1.0-RC3
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/com.typesafe.play/play-ebean_2.13/6.1.0-RC3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.13/6.1.0-RC3/play-ebean_2.13-6.1.0-RC3.pom
[error]   forbidden: https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.13/6.1.0-RC3/play-ebean_2.13-6.1.0-RC3.pom
[error]   not found: ~/.m2/repository/com/typesafe/play/play-ebean_2.13/6.1.0-RC3/play-ebean_2.13-6.1.0-RC3.pom
```

The bintray repo is definitely giving 403, so that's useless.  I've tried both 6.1.0-RC2 and 6.1.0-RC3.  So is this resolvable without reverting to 6.0.0 and scala 2.12?

**Comment by mkurz** [comment]
play-ebean 6.2.0-RC4 released, please have a look at the release notes how to upgrade: https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4. Please test and let us know if it works for you, thanks!

**Comment by pogurek** [comment]
Play 2.8.13 Scala 2.13.8 SBT 1.6.2
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.2.0-RC4")
Failing with this error:
`[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-play-ebean;sbtVersion=1.0;scalaVersion=2.12:6.2.0-RC4
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-play-ebean_2.12_1.0/6.2.0-RC4/sbt-play-ebean-6.2.0-RC4.pom
[error]   not found: C:\Users\pogur\.ivy2\localcom.typesafe.sbt\sbt-play-ebean\scala_2.12\sbt_1.0\6.2.0-RC4\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-play-ebean/scala_2.12/sbt_1.0/6.2.0-RC4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-play-ebean/scala_2.12/sbt_1.0/6.2.0-RC4/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)`

**Comment by hertg** [comment]
@pogurek 
You need to change `com.typesafe.sbt` to `com.typesafe.play` as stated in the [release notes](https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4).

**Comment by PromanSEW** [comment]
@mkurz I can help with this PR

**Comment by justinnichols** [comment]
@mkurz I'm also looking into this, but using your PR (checked out as a branch), it compiles just fine for me on both Java 11 and Java 17.

I made a slight modification to build.sbt (which wouldn't impact your compilation) such that
`testOptions in Test += Tests.Argument(TestFrameworks.JUnit, "-a", "-v"),`
becomes
`Test / testOptions += Tests.Argument(TestFrameworks.JUnit, "-a", "-v"),`

Git log shows latest commit:
```
commit c2e07dcd8448fc05ff781d922bda77141e1a9b60 (HEAD -> 2.8.x_matthias)
Author: Matthias Kurz <m.kurz@irregular.at>
Date:   Fri Mar 4 15:54:16 2022 +0100

    Readd currentTimeMillis hack
```

Java 11 compilation:
```
play-java-ebean-example ᐅ sbt clean compile
[info] welcome to sbt 1.6.2 (Eclipse Adoptium Java 11.0.14)
[info] loading global plugins from /Users/justin/.sbt/1.0/plugins
[info] loading settings for project play-java-ebean-example-build from plugins.sbt ...
[info] loading project definition from /Users/justin/src/Personal/github/playframework/play-samples/play-java-ebean-example/project
[info] loading settings for project root from build.sbt ...
[info]   __              __
[info]   \ \     ____   / /____ _ __  __
[info]    \ \   / __ \ / // __ `// / / /
[info]    / /  / /_/ // // /_/ // /_/ /
[info]   /_/  / .___//_/ \__,_/ \__, /
[info]       /_/               /____/
[info]
[info] Version 2.8.13 running Java 11.0.14
[info]
[info] Play is run entirely by the community. If you want to keep using it please consider donating:
[info] https://www.playframework.com/sponsors
[info]
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed Mar 8, 2022, 11:57:08 AM
[info] compiling 10 Scala sources and 8 Java sources to /Users/justin/src/Personal/github/playframework/play-samples/play-java-ebean-example/target/scala-2.13/classes ...
[success] Total time: 8 s, completed Mar 8, 2022, 11:57:16 AM
```

Java 17 compilation:
```
play-java-ebean-example ᐅ sbt clean compile
[info] welcome to sbt 1.6.2 (Eclipse Adoptium Java 17.0.2)
[info] loading global plugins from /Users/justin/.sbt/1.0/plugins
[info] loading settings for project play-java-ebean-example-build from plugins.sbt ...
[info] loading project definition from /Users/justin/src/Personal/github/playframework/play-samples/play-java-ebean-example/project
[info] loading settings for project root from build.sbt ...
[info]   __              __
[info]   \ \     ____   / /____ _ __  __
[info]    \ \   / __ \ / // __ `// / / /
[info]    / /  / /_/ // // /_/ // /_/ /
[info]   /_/  / .___//_/ \__,_/ \__, /
[info]       /_/               /____/
[info]
[info] Version 2.8.13 running Java 17.0.2
[info]
[info] Play is run entirely by the community. If you want to keep using it please consider donating:
[info] https://www.playframework.com/sponsors
[info]
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]   Java version is 17. Play supports only 8 and 11.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed Mar 8, 2022, 11:54:38 AM
[info] compiling 10 Scala sources and 8 Java sources to /Users/justin/src/Personal/github/playframework/play-samples/play-java-ebean-example/target/scala-2.13/classes ...
[success] Total time: 7 s, completed Mar 8, 2022, 11:54:45 AM
```

Perhaps I'm doing something wrong when compared to your setup, but compilation seems fine to me.  `sbt test` is also successful.

**Comment by mkurz** [comment]
@justinnichols thanks for your help. However I with the help of @PromanSEW I already fixed the pull request and merged it. so you already testet the fixed version of the pr. Anyway great that you checked as well, I am happy if you want to support :+1:

**Comment by justinnichols** [comment]
I see.  My apologies.  I must have missed the update where it said this was fixed.  I'll bow out.

**Comment by mkurz** [comment]
Closing since it looks like this is working now.
