### ISSUE TITLE
io.ebean.enhance.asm.ClassReader | Unsupported class file major version 59 | Support java15?

### ISSUE THREAD

**Issue by Santhoshas** [playframework/play-ebean#215]
I am getting the below error while compiling the project using JDK 15 and other components. Which version is invalid here?

sbt -> 1.3.13
scala -> 2.12.13
Play -> 2.7.0
JDK -> 15
addSbtPlugin("com.typesafe.sbt" % "sbt-play-enhancer" % "1.2.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "5.0.2")

Error:
java.lang.IllegalArgumentException: Unsupported class file major version 59
at io.ebean.enhance.asm.ClassReader.(ClassReader.java:184)
at io.ebean.enhance.asm.ClassReader.(ClassReader.java:166)
at io.ebean.enhance.asm.ClassReader.(ClassReader.java:152)
at io.ebean.enhance.Transformer.detect(Transformer.java:352)
at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:187)
at io.ebean.enhance.Transformer.transform(Transformer.java:152)
at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:84)
at scala.Function1.$anonfun$compose$1(Function1.scala:49)
at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)

**Comment by SethTisue** [comment]
looks like Ebean uses a version of ASM that is too old to understand JDK 15 bytecode

**Comment by mkurz** [comment]
Play 2.8 does not support JDK > 11, please use Java 11 or 8.

**Comment by Santhoshas** [comment]
> looks like Ebean uses a version of ASM that is too old to understand JDK 15 bytecode

Which version of eBean should be used ?

**Comment by SethTisue** [comment]
@Santhoshas I don't know — you might need to do your own research on that

**Comment by rbygrave** [comment]
@Santhoshas  @SethTisue  FYI Ebean's ebean-agent supports Java 16, it seems that the version of ebean-agent being used here is quite old.

**Comment by SethTisue** [comment]
I see — perhaps someone would like to send a pull request with an upgrade.
