### ISSUE TITLE
NoClassDefFoundError: io/ebean/EbeanServer

### ISSUE THREAD

**Issue by PromanSEW** [playframework/play-ebean#278]
I updated Ebean to 13.6.0, and got this exception:
```
play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: io/ebean/EbeanServer]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:258)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:302)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1307)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
Caused by: java.lang.NoClassDefFoundError: io/ebean/EbeanServer
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:811)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:730)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:430)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:177)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:670)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:627)
Caused by: java.lang.ClassNotFoundException: io.ebean.EbeanServer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:811)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:730)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:430)
```
Links:
https://github.com/ebean-orm/ebean/releases/tag/ebean-parent-13.6.0
https://github.com/ebean-orm/ebean/pull/2662

**Comment by PromanSEW** [comment]
I can try to provide PR with fix

**Comment by PromanSEW** [comment]
I checked RC5 and `"io.ebean" % "ebean-platform-postgres" % "13.6.0"` as well
With RC5 the stacktrace is the same :(
With postgres dependency which has the only used components from Ebean:
```
play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: io/ebean/EbeanServer]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:258)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:302)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1307)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
Caused by: java.lang.NoClassDefFoundError: io/ebean/EbeanServer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
Caused by: java.lang.ClassNotFoundException: io.ebean.EbeanServer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
```
Compatibility fix had no effect :(
I don't know why
Checked on Java 11 and Java 17 (Adoptium)

**Comment by mkurz** [comment]
Did you remove the `target` folder?

**Comment by PromanSEW** [comment]
Yes

**Comment by PromanSEW** [comment]
@mkurz 
I investigated this issue
At this moment I found that:
There is conflict of `EbeanDynamicEvolutions#generateEvolutionScript(Database)` and deprecated `EbeanDynamicEvolutions#generateEvolutionScript(EbeanServer)` methods
If I remove deprecated method and check `publishLocal` snapshot, the `EbeanDynamicEvolutions` class is gone from stacktrace in debugger, but error is still present. I could not find where this class is used in other places.
I will try to find more information

**Comment by PromanSEW** [comment]
Finally found the problem:

> There is conflict of `EbeanDynamicEvolutions#generateEvolutionScript(Database)` and deprecated `EbeanDynamicEvolutions#generateEvolutionScript(EbeanServer)` methods
> If I remove deprecated method and check `publishLocal` snapshot, the `EbeanDynamicEvolutions` class is gone from stacktrace in debugger

It is the one binary incompatibility for 13.6.0
Error went away with these conditions:
```sbt
val ebeanVersion = "13.6.0"
dependencyOverrides ++= Seq(
  "io.ebean" % "ebean" % ebeanVersion,
  "io.ebean" % "ebean-agent" % ebeanVersion,
  "io.ebean" % "ebean-ddl-generator" % ebeanVersion
)
```
Removed deprecated method in `EbeanDynamicEvolutions` and added parameterless constructors to all models classes because of error:
```
Caused by: java.lang.IllegalStateException: Error trying to create the prototypeEntityBean for class models.HistoryEntry
	at io.ebeaninternal.server.deploy.BeanDescriptor.createPrototypeEntityBean(BeanDescriptor.java:431)
```

Also, there should be discussion for dependencies, or info in readme how to update to Ebean 13 right.
It has new dependency graph, there root package `io.ebean:ebean` is kind of "Bill of materials", which contains all dependencies
It is recommended to use needed modules instead, for example `io.ebean:ebean-platform-postgres`, which has only really used modules

**Comment by PromanSEW** [comment]
I could not fix `IllegalStateException` yesterday, but it is Ebean problem, not Play plugin
I will notify here how to fix this exception, maybe it will help anyone
I did not find any solutions in Google

**Comment by rbygrave** [comment]
What is the full stack trace @PromanSEW ?  Can you include it / post it up ?
