### ISSUE TITLE
Joda Type isn't supported on the hood anymore since Ebean 13.9.0

### ISSUE THREAD

**Issue by felipebonezi** [playframework/play-ebean#330]
Joda type was moved to a separate module.
But it looks like it affects the current RC version, but it says that only version 13.9.0 is affected.

`Caused by: java.lang.IllegalArgumentException: Joda date/time type `org.joda.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-joda" to enable handling (through reference chain: java.util.ArrayList[0]->models.viewmodels.reseller.RemunerationViewModel["month"])
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3394)
	at play.libs.Json.toJson(Json.java:92)
	... 9 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Joda date/time type `org.joda.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-joda" to enable handling (through reference chain: java.util.ArrayList[0]->models.viewmodels.reseller.RemunerationViewModel["month"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)`

IMHO we need to explain to those who use this library about this as a migration guide or even in the README file.

[Ebean 13.9.0](https://github.com/ebean-orm/ebean/releases/tag/ebean-parent-13.9.0)
> Move Joda time support into the separate optional ebean-joda-time module
> When using Joda time types please check the classpath to ensure that it contains the ebean-joda-time dependency.

**Comment by felipebonezi** [comment]
Wrong issue.
