### ISSUE TITLE
Enhance models without configuring DB connection

### ISSUE THREAD

**Issue by hertg** [playframework/play-ebean#402]
As I understand it, this module takes care of "running" the [ebean enhancement](https://ebean.io/docs/enhancement/). Is there a possibility to enhance models without configuring the database connection statically?

> [!NOTE]
> I am currently working with
> - **sbt** 1.9.6
> - **Play** 2.9.0-RC2
> - **sbt-play-ebean** 7.0.0-RC2
> - **JDK** 21

---

**Use-Case**

My use-case is that I use SQLite as my `default` datasource, but my Play application includes an installation wizard (via web forms, which are part of the play app) that should allow to import data from the previous app versions, which used a different database structure and ran on MySQL. The connection parameters for the old database should not be configured statically in application.conf, but instead the connection (host, schema, username, password) is configured in the installation wizard, and the connection is established during runtime for the import.

I have tried the following:

**Not configuring anything about the old datasource (no `db.mysql` config, no `ebean.mysql` config)**
This leads to the issue that the models in `models.mysql` are not  enhanced. I can start the application, but once I manually connect to the `mysql` database, the following exception is thrown.

```java
// sanitize inputs
final DataSourceConfig dsc = new DataSourceConfig();
dsc.setUsername(form.getUsername());
dsc.setPassword(form.getPassword());
dsc.setUrl(connectionString(form.getHost(), form.getSchema()));
final DatabaseConfig databaseConfig = new DatabaseConfig();
databaseConfig.setDataSourceConfig(dsc);
databaseConfig.setName("mysql");
databaseConfig.setDefaultServer(false);
DatabaseFactory.create(databaseConfig);
```

```
play.api.PlayException: Execution exception[[CompletionException: io.ebean.config.BeanNotEnhancedException: Bean class models.mysql.DeprecatedIdentity is not enhanced? Check packages specified in ebean.mf. If you are running in IDEA or Eclipse check that the enhancement plugin is installed. See https://ebean.io/docs/trouble-shooting#not-enhanced]]
	at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$3(HttpErrorHandler.scala:407)
	at scala.Option.getOrElse(Option.scala:201)
	at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:407)
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181)
	at utils.ErrorHandler.lambda$onServerError$1(ErrorHandler.java:47)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at utils.ErrorHandler.onServerError(ErrorHandler.java:47)
Caused by: java.util.concurrent.CompletionException: io.ebean.config.BeanNotEnhancedException: Bean class models.mysql.DeprecatedIdentity is not enhanced? Check packages specified in ebean.mf. If you are running in IDEA or Eclipse check that the enhancement plugin is installed. See https://ebean.io/docs/trouble-shooting#not-enhanced
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at scala.concurrent.impl.FutureConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.FutureConvertersImpl$CF.apply(FutureConvertersImpl.scala:23)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
Caused by: io.ebean.config.BeanNotEnhancedException: Bean class models.mysql.DeprecatedIdentityLockdown is not enhanced? Check packages specified in ebean.mf. If you are running in IDEA or Eclipse check that the enhancement plugin is installed. See https://ebean.io/docs/trouble-shooting#not-enhanced
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1376)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1261)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1189)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:691)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:293)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:129)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:104)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:29)
	at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:136)
	at io.ebean.DatabaseFactory.create(DatabaseFactory.java:85)
```

**Configuring the ebean model package, but no db connection (no `db.mysql` config, `ebean.mysql = ["models.mysql.*"]`)**
This doesn't work, an exception is thrown when I start the application.

```
Caused by: NullPointerException: Cannot invoke "play.db.Database.getDataSource()" because the return value of "play.db.DBApi.getDatabase(String)" is null
	at DefaultEbeanConfig$EbeanConfigParser.setServerConfigDataSource(DefaultEbeanConfig.java:99)
	... 75 more
```

**Comment by PromanSEW** [comment]
`compile` and `dist` command compiles and enhances classes without connection settings needed, isn't it? Compiled enhanced classes are compatible with all DBs.
I see that you problem is in configuration only, not in binary code, alright?

**Comment by hertg** [comment]
@PromanSEW It does compile, but it doesn't run (at least in dev mode).

The issue occurring when using the second way seems to come from evolutions. It looks like it attempts to set up a DB and apply evolutions for the `mysql` datasource, even though I explicitly disabled it.

```hocon
db.default {
  driver = org.sqlite.JDBC
  url = "jdbc:sqlite:./.data/data.db"
  initSQL = "PRAGMA foreign_keys = true; PRAGMA journal_mode=WAL;" # enable foreign keys
}

play.evolutions.db.mysql.enabled = false
play.evolutions.db.default {
  enabled = true # default: true
  schema = "main" # default: null
  autocommit = false # default: true
}

ebean {
  mysql = ["models.mysql.*"]
  default = ["models.ebean.*"]
}
```


> [!NOTE]
> `default` is my SQLite datasource where I use evolutions, it works as intended
> `mysql` is my MySQL datasource which I only want to connect to manually during runtime, its models shall still be enhanced

I get the following stacktrace.

```
play.api.PlayException: Execution exception[[CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: ConfigException$BadValue: Invalid value at 'ebean.mysql': Cannot invoke "play.db.Database.getDataSource()" because the return value of "play.db.DBApi.getDatabase(String)" is null
  while locating DefaultEbeanConfig$EbeanConfigParser
  at EbeanModule.bindings(EbeanModule.java:21):
Binding(interface EbeanConfig to ProviderConstructionTarget(class DefaultEbeanConfig$EbeanConfigParser) eagerly)
      \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
  at EbeanDynamicEvolutions.<init>(EbeanDynamicEvolutions.java:42)
      \_ for 1st parameter
  at EbeanDynamicEvolutions.class(EbeanDynamicEvolutions.java:35)
  while locating EbeanDynamicEvolutions
  at EbeanModule.bindings(EbeanModule.java:20):
Binding(class DynamicEvolutions to ConstructionTarget(class EbeanDynamicEvolutions) eagerly)
      \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
  while locating DynamicEvolutions

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: ConfigException$BadValue: Invalid value at 'ebean.mysql': Cannot invoke "play.db.Database.getDataSource()" because the return value of "play.db.DBApi.getDatabase(String)" is null
	at DefaultEbeanConfig$EbeanConfigParser.setServerConfigDataSource(DefaultEbeanConfig.java:101)
	at DefaultEbeanConfig$EbeanConfigParser.parse(DefaultEbeanConfig.java:82)
	at DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:61)
	at DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:45)
	at ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at BoundProviderFactory.get(BoundProviderFactory.java:59)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at Guice.createInjector(Guice.java:87)
	at Guice.createInjector(Guice.java:78)
	at GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:176)
	at GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at DevServerStart$DevServerApplicationProvider$1.$anonfun$reload$2(DevServerStart.scala:233)
	at Threads$.withContextClassLoader(Threads.scala:22)
	at DevServerStart$DevServerApplicationProvider$1.reload(DevServerStart.scala:225)
	at DevServerStart$DevServerApplicationProvider$1.get(DevServerStart.scala:190)
	at AkkaHttpServer.handleRequest(AkkaHttpServer.scala:320)
	at AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
	at MapAsync$$anon$30.onPush(Ops.scala:1309)
	at GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at GraphInterpreter.execute(GraphInterpreter.scala:390)
	at GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at Actor.aroundReceive(Actor.scala:537)
	at Actor.aroundReceive$(Actor.scala:535)
	at ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at ActorCell.receiveMessage(ActorCell.scala:579)
	at ActorCell.invoke(ActorCell.scala:547)
	at Mailbox.processMailbox(Mailbox.scala:270)
	at Mailbox.run(Mailbox.scala:231)
	at Mailbox.exec(Mailbox.scala:243)
	at java.base/ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: NullPointerException: Cannot invoke "play.db.Database.getDataSource()" because the return value of "play.db.DBApi.getDatabase(String)" is null
	at DefaultEbeanConfig$EbeanConfigParser.setServerConfigDataSource(DefaultEbeanConfig.java:99)
	... 58 more

```

**Comment by hertg** [comment]
@PromanSEW I did, unfortunately it doesn't help. I figured that my assumption about evolutions causing the problem was not entirely true. I managed to resolve my issue by making a small change to `DefaultEbeanConfig`. I'm about to open a PR with my solution.
